Repoman:locked the version of tox for el7
Newer version of tox failing with the message below.
With locking the verison failing on el7
ERROR: Cannot uninstall 'virtualenv'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which
would lead to only a partial uninstall.

Change-Id: I2f9e706fe66e574536001faf96c51caafc1693c1
Signed-off-by: Galit <grosenth@redhat.com>